import { createTask, deleteTask, updateTask, getTasksByList, getTasksByWorkspace, getTaskWithWorkspace } from "../../db/repositories/todo.repository.js";
import { getListWithWorkspace } from "../../db/repositories/list.repository.js";
import { requireWorkspaceEditor, requireWorkspaceMember } from "../workspace/workspace.service.js";
import makeError from "../../utils/makeError.js";
import { clearTaskCaches, getListTasksCache, getWorkspaceTasksCache, setListTasksCache, setWorkspaceTasksCache } from "../../cache/todo.cache.js";

export const getTaskWorkspace = async (taskId: string) => { const task = await getTaskWithWorkspace(taskId); if (!task) throw makeError("Task not found", 404); return task as { id: string; workspace_id: string; list_id: string }; };
export const createListTask = async (listId: string, title: string, description: string | null, position: number, priority: string, createdBy: string) => { const list = await getListWithWorkspace(listId); if (!list) throw makeError("List not found", 404); await requireWorkspaceEditor(list.workspace_id, createdBy); const task = await createTask(listId, title, description, position, false, priority, createdBy); await clearTaskCaches(list.workspace_id, listId); return task; };
export const getListTasks = async (listId: string, userId: string) => { const list = await getListWithWorkspace(listId); if (!list) throw makeError("List not found", 404); await requireWorkspaceMember(list.workspace_id, userId); const cached = await getListTasksCache<Awaited<ReturnType<typeof getTasksByList>>>(listId); if (cached) return cached; const tasks = await getTasksByList(listId); await setListTasksCache(listId, tasks); return tasks; };
export const getWorkspaceTasks = async (workspaceId: string, userId: string) => { await requireWorkspaceMember(workspaceId, userId); const cached = await getWorkspaceTasksCache<Awaited<ReturnType<typeof getTasksByWorkspace>>>(workspaceId); if (cached) return cached; const tasks = await getTasksByWorkspace(workspaceId); await setWorkspaceTasksCache(workspaceId, tasks); return tasks; };
export const updateListTask = async (taskId: string, data: { list_id?: string | undefined; title?: string | undefined; description?: string | null | undefined; position?: number | undefined; completed?: boolean | undefined; priority?: string | undefined }, userId: string) => { const current = await getTaskWorkspace(taskId); await requireWorkspaceEditor(current.workspace_id, userId); if (data.list_id) { const destination = await getListWithWorkspace(data.list_id); if (!destination || destination.workspace_id !== current.workspace_id) throw makeError("Destination list is not in this workspace", 400); } const task = await updateTask(taskId, data.list_id, data.title, data.description, data.position, data.completed, data.priority); if (!task) throw makeError("Task not found", 404); await clearTaskCaches(current.workspace_id, current.list_id, task.list_id); return task; };
export const removeTask = async (taskId: string, userId: string) => { const current = await getTaskWorkspace(taskId); await requireWorkspaceEditor(current.workspace_id, userId); const task = await deleteTask(taskId); if (!task) throw makeError("Task not found", 404); await clearTaskCaches(current.workspace_id, current.list_id); return task; };
